### ISSUE TITLE
Record / response x_axis treatment

### ISSUE THREAD

**Issue by xjules** [equinor/ert-storage#69]
So far we discussed that `x_axis` should come into storage in the domain semantics, ie. datetime, string, int, indices, etc.
A suggestion being that `response` should refer only to observed values of the record (ie. simplistic put it `record[obs.x_axis]`) and thus we could have:

`/ensembles/{ensemble_id}/records/FOPR` to return all the values

while 

`/ensembles/{ensemble_id}/response/FOPR` to return only observed values.

The actual domain semantics of `x_axis` could be stored as metadata or as part of numpy array, for instance:
```python
arr = np.array([(1., 2., np.datetime64('2007-07-13')), (2., 3., np.datetime64('2007-07-14'))] ,dtype=[('r0', 'f4'), ('r1', 'f4'), ('index', 'datetime64[D]')])

# accessing 
In: arr["index"]
Out: array(['2007-07-13', '2007-07-14'], dtype='datetime64[D]')

In: arr["r0"].sum()
Out: 3.0
```

**Comment by dotfloat** [comment]
We require two different classes of data:
- **[Non-interpolable]**: `x_axis` is a vector of unique labels. The labels can be any data for which we can do equality.
- **[Interpolable]**: `x_axis` is a vector of interpolable values. The labels must have a total ordering.

Non-interpolable data allows the user to upload any labels they please. The downside is that ERT Storage can't filter or resize the data (eg. only getting 100 points for visualisation purposes). If an observation has _n_ data points, the observed set of responses might contain less than _n_ points, since the labels of observations and records have to match exactly.

Interpolable data (currently only timeseries. Could also be spatial data, etc) requires the labels to be of known type to ERT Storage. We can allow the user to fetch only some window of the data (eg. dates between 2019 and 2020, and only 100 of them). If an observation has _n_ data points, the observed set of responses will be exactly _n_ points, as the mismatched datapoints get interpolated.

**Comment by markusdregi** [comment]
> ... `response` should refer only to observed values

In the standard usage of the word I'm quite certain that the `response` would refer to the response of the model, not the observed values. Feel free to chime in @eivindsm!

**Comment by markusdregi** [comment]
Also, in general I think it would be wise to consider having the linkage between the model responses and the observations live within the experiment or update, and not the observation nor model response objects. As the later would prevent responses and observations to be able to exist independently.

**Comment by markusdregi** [comment]
Last, would be keen to get some context on the motivation of this discussion. Is this something we need to resolve now?

**Comment by dotfloat** [comment]
This is something we'd like to resolve ASAP, so after today's standup hopefully.

**Comment by dotfloat** [comment]
We had a discussion and decided that the interpolation concept shouldn't be something we care about in ERT Storage:
* We don't want to hide that interpolation from the user. (This could be avoided by specifiying this data as extra headers for example, but it mostly complicates things)
* If the user _wants_ to do interpolation, we don't know what type of interpolation they want, and there are too many interpolation methods to bother. (We could add some of the most popular ones, as doing interpolation on the ERT Storage side should in theory be faster, but again, complicates things)

In the short to medium term, we don't do any interpolation. If there's a mismatch between the response and observation, we should explode and return an error. In my opinion, ERT Storage should do validation when uploading the responses to make sure that the data is consistent. If this is something we all want, we should create a separate issue on validation.

**Comment by xjules** [comment]
Summary from the meeting 19.04.2021:

* The interpolation won't be considered for now, but remains to be discussed further in the future
* labels for `x_axis` should match for both observations and responses correspondingly. If they don't match
     * we should provide an error either when accessing the compute endpoint (eg. misfits)
     * we should provide an error when storing the observation for the particular record that there is a mismatch

**Comment by markusdregi** [comment]
I agree with the summary 👍 Please close and/or rewrite the issue and/or create a new issue such that it represents an actionable endeavor or a future discussion @xjules
