### ISSUE TITLE
Should workspaces be a concept in ERT Storage?

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#70]
In my mind, workspaces are a tree-structure to group together experiments. For example, each asset could have a top-level workspace (eg. [`trollfelt 2`](https://en.wikipedia.org/wiki/Troll_2)), where the users with access to the asset can have their projects. Users can create and delete their own workspaces. By default, we create an empty personal workspace for each AD user.

The point of a workspace is to logically group the experiments, so we don't end up with a long list of experiments.

This can be implemented as follows:
- The ERT frontend service (which is separate from ERT Storage), can tie experiment IDs to their own internal concept of workspace. ERT Storage doesn't know about workspaces.
- ERT Storage contains this information. Webviz-ert and other services can obtain this information directly.

The argument in favour of alternative 1 is that this helps keep the scope of ERT Storage minimal. Minimal GUI/user-related concepts make their way into the database.

The argument in favour of alternative 2 is that it'll allow consumers (eg. webviz-ert) to obtain the information easily. It could potentially make it easier to have policy-based security. Ie, if a user has "view experiment" access to a workspace, then it's easier to remove this later. If the policy is tied to an experiment (ie. "view experiment") it'll make it more difficult to remove it later on in an easy way.

See also: 
- https://github.com/equinor/ert/issues/1405

**Comment by jondequinor** [comment]
Small addition to the favorable argument presented for alternative 1. The premise is that 1) the workspace concept is fuzzy now and for some time in the future and 2) business logic is a infinite generator of edge case. It's thus cheaper to develop and maintain some ugly workspace implementation as a set of code and files (azure blobs) in _one_ place, rather than to distribute it over ert and ert-storage—and by extension ert-storage's APIs, schemas and migrations.

Eventually it should be put in ert-storage, but I think only as a mature and stable concept. If premise 1 is false, then forgive me.

**Comment by markusdregi** [comment]
I agree with the arguments present.

The only assumption currently is that the client is able to explore data related to a specific workspace/project. But, this is easily resolvable by letting there be a single workspace utilising an storage instance for now 👍🏻

I guess the answer is no for now? If so, should we close the issue?
